### ISSUE TITLE
Are drive letters standard within JNCC?

### ISSUE THREAD

**Issue by sumothecat** [JNCC-dev-team/catalogue#102]
In the catalogue, we record the file system path like so `J:\Reference\Marine\...`

Ulric has raised the question of how consistent this is across the organisation. Is there a possibility that different teams have a different set of drive mappings??

Obviously individuals could map their own custom drive letters, but can we confirm the standard ones in the organisation please?

Obviously the nightmare scenario would be that there is a drive which is ambiguous, e.g. the same letter used by different teams for different paths.

**Comment by helen-ellwood** [comment]
Yes J is used consistently. I'm pretty sure new starters get given a sheet with JNCC's standard drive mapping. I suppose Carl or Sue would know.

**Comment by Carl-Cilenti** [comment]
There are common drive letters within the JNCC, these get mapped for everyone. These include:
the G:\ drive - jncc-corpfile\Corporate Apps
The J:\ drive - jncc-corpfile\gis
The Y:\ drive - jncc-corpfile\Teams and Staff
The P:\ drive - jncc-corpfile\Purchase-Logs
The Z:\ drive - jncc-corpfile\JNCC Corporate Data

Then there are some variations depending on location eg Pboro and Aberdeen. Then there are some work specific ones e.g Finance, Marine survey etc.

**Comment by sumothecat** [comment]
Answer from Carl. All appears to be OK.
