### ISSUE TITLE
Vocabulary consistency

### ISSUE THREAD

**Issue by GMDuncan** [JNCC-dev-team/catalogue#103]
There are curretly two similar keyword vocab entries: "Multibeam echosounder" and "Multibeam echo sounder" due to inconsistencies in the original MESH Catalogue. I have change all records with keyword "Multibeam echosounder" to "Multibeam echo sounder", however the first version still appears in the vocab list. Is it possible to remove this entry from the vocab list?

**Comment by sumothecat** [comment]
Will be resolved with re-import. I already spotted the variations and this was one I missed!

                case "multibeam echo sounder":
                case "multibeam echo scounder":
                case "multibeam echosounder":
                    return "Multibeam echo sounder";
