### ISSUE TITLE
Import the JNCC publications catalogue

### ISSUE THREAD

**Issue by sumothecat** [JNCC-dev-team/catalogue#54]

**Comment by felixMasonJncc** [comment]
Basically done on beta with the following caveats

-Records will need to be manually reviewed - text tidied up in the abstract
-File paths probably need to be imported based on some convention but that depends on the implementation of the publications catalogue in the new cms
-Publication records are marked as publishable and require a web location, this will have to be fed back from the cms in someway possibly, or produced by convention
