### ISSUE TITLE
Tweaks to PubCat import

### ISSUE THREAD

**Issue by sumothecat** [JNCC-dev-team/catalogue#86]
Data format could be Documents (medin)
Top copy = true? usually?
Status is Publishable?
Type is Dataset? Maybe even have another one (Publication)

Remove === Summary === heading from abstract when it begins with it
Remove multiple line breaks from abstract
remove keywords that differ only by case (JNCC, jncc)
Quite a few records have keywords like `JNCC Report 455 A global review of long-term Marine Protected Area monitoring programmes: The application of a good framework to marine biological monitoring Volume 1: Main Report and Volume 2: Appendix 1-4 Prue Addison`

**Comment by felixMasonJncc** [comment]
> Quite a few records have keywords like JNCC Report 455 A global review of long-term Marine 
> Protected Area monitoring programmes: The application of a good framework to marine biological 
> monitoring Volume 1: Main Report and Volume 2: Appendix 1-4 Prue Addison

How would you expect this to be dealt with pragmatically? Limit keyword field length?

**Comment by felixMasonJncc** [comment]
Most of this is done. However I've left the summary heading and those multiple line breaks that remain. This is because there are many instances where the abstract text will need other interventions so whilst it's nice it's not a valuable use of development time.

Changes on Beta
