### ISSUE TITLE
Keyword suggestions: 'publication' does not find Publications tag

### ISSUE THREAD

**Issue by sumothecat** [JNCC-dev-team/catalogue#96]
http://localhost:55466/app/#/?q=publication
http://localhost:55466/app/#/?q=publications
doesn't find anything, but
http://localhost:55466/app/#/?q=publicatio does!

**Comment by felixMasonJncc** [comment]
Problem here is the ngram filer in the custom keyword analyser. Max ngram was 10 for some reason however it doesn't seem to get publicatoin but increasing the ngram size to 30 resolves the issue for now. However it will mean a growth in index size. :(
